services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env.prod
  cassandra:
    image: 'cassandra:latest'
    container_name: mycassandra
    ports:
      - '9042:9042'
    environment:
      CASSANDRA_USERNAME: docker
      CASSANDRA_PASSWORD: docker
