services:
  cassandra:
    image: 'cassandra:latest'
    container_name: cassandra
    networks:
      - reduce-network
    ports:
      - "9042:9042"
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -u cassandra -p cassandra" ]
      interval: 20s
      timeout: 20s
      retries: 10
      start_period: 60s
  reduce_api:
    container_name: reduce-app
    image: guilhermezuriel/reduce-app:latest
    ports:
      - "8080:8080"
    volumes:
      - ./target:/app
    networks:
      - reduce-network
    depends_on:
       cassandra:
        condition: service_healthy
    env_file:
      - .env.local.docker
networks:
  reduce-network:
      driver: bridge
