spring:
  application:
    name: "Reduce.me"
  cassandra:
    port: 9042
    contact-points: cassandra
    keyspace-name: my_keyspace
    schema-action: create_if_not_exists
    username: cassandra
    password: cassandra
reduceme:
  api_url_base: http://localhost:8080/