spring:
  application:
    name: "Reduce.me"
  cassandra:
    port: ${DB_PORT}
    contact-points: ${DB_CONTACT}
    keyspace-name: ${DB_KEYSPACE}
    schema-action: create_if_not_exists
reduceme:
  api_url_base: ${API_URL}